name: ros2-talker-listener
version: '0.1'
summary: ROS 2 Talker/Listener Example
description: |
 This example launches a ROS 2 talker and listener.

confinement: strict
grade: stable
base: core22

parts:
 talker-listener:
   plugin: colcon
   source: .
   stage-packages: [ros-humble-ros2launch]

apps:
 ros2-talker-listener:
   command: opt/ros/humble/bin/ros2 launch talker-listener talker_listener.launch.py
   plugs: [network, network-bind]
   extensions: [ros2-humble]
